### ISSUE TITLE
MIIM initialization

### ISSUE THREAD

**Issue by Cargr** [Microchip-MPLAB-Harmony/net#40]
Hi,

after updating a project from Net v3.8.0 to v3.9.0 there was a compiling error.

> /initialization.c:606:32: error: 'drvMiimInitData_0' undeclared here (not in a function); did you mean 'drvMemory0InitData'?

After comparing the initialization.c from both versions, i could find out that the forward declarations is missing.

Before:
```
// *****************************************************************************
// *****************************************************************************
// Section: Driver Initialization Data
// *****************************************************************************
// *****************************************************************************

/* Forward declaration of MAC initialization data */
const TCPIP_MODULE_MAC_PIC32INT_CONFIG tcpipMACPIC32INTInitData;
```

Corrected:
```
// *****************************************************************************
// *****************************************************************************
// Section: Driver Initialization Data
// *****************************************************************************
// *****************************************************************************

/* Forward declaration of MIIM initialization data */
static const DRV_MIIM_INIT drvMiimInitData_0;

/* Forward declaration of MAC initialization data */
const TCPIP_MODULE_MAC_PIC32INT_CONFIG tcpipMACPIC32INTInitData;
```
In my case the section began at line 115.

Best regards
Carsten Grote

**Comment by adrian-aur** [comment]
To port an existing project to net v3.9.0 which uses the new Net plugin there are few steps necessary.
Please see the plugin documentation at
https://github.com/Microchip-MPLAB-Harmony/net/blob/master/docs/index.md 
See the last section: TCPIP Configurator for getting started and migration guide:
https://github.com/Microchip-MPLAB-Harmony/net/blob/master/docs/GUID-3A0DFD6E-F6BC-4FE9-BAE4-BE22C34C21C0.md
